version: '3.1'

services:

  ghostcms2mastodon:
    image: okxo/ghostcms2mastodon:latest
    restart: always
    volumes:
      - .secret:/.secret
    restart: always
    ports:
      - 5000:5000
    env_file:
      - .env
    networks:
      vpcbr:
        ipv4_address: 10.9.9.99
    tty: true


networks:
  vpcbr:
     driver: bridge
     ipam:
       config:
         - subnet: 10.9.9.0/24
           gateway: 10.9.9.1
